<?php 
$respose = "Cosa, cosa, cosa…
Tengo mucho que decir, me gustaría iniciar diciendo que Dios me ha bendecido con tu amistad, porque tú embelleces mi existencia, para esto me gustaría dedicarte el poema de Gabriel García Marques, que dice así: “Si algún día quieres llorar, llámame, no prometo hacerte reír, pero puedo llorar contigo. Si un día logras escapar, llámame, no prometo pedirte que te quedes, pero podré escapar contigo. Si un día no quieres hablar con nadie, llámame, y estaremos en silencio. Y si un día me llamas y no contesto, ven corriendo a mí, porque sin duda te necesitaré”, eres y serás muy importante para mí, sin importar cuales sean las circunstancias, ni los contextos que nos rodeen, siempre vas a ser mi mejor amiga, estes casada, o este casado, o tengas novio, tenga novia, no importa, así será. Sabes, creo que en varios sentidos, nuestra amistad es descrita en la biblia, una amistad es de crecimiento mutuo, como lo dice en Proverbios27:17 “Hierro con hierro se aguza; Y así el hombre aguza el rostro de su amigo”, me gusta mucho que cuando yo tengo pensamientos torcidos y blasfemos y siempre por tus oraciones y tu atención estos se van, por cierto, por ello te agradezco demasiado cosa. Estás son cosas que solo puedo hablar contigo, porque nadie de mi entorno próximo me podría ayudar con ello, todos en mi casa apoyarán esos pensamientos, y es así como lo dice en proverbios27:10 “No dejes a tu amigo, ni al amigo de tu padre; Ni vayas a la casa de tu hermano en el día de tu aflicción. Mejor es el vecino cerca que el hermano lejos”, he intentado hablar de algunos temas con mi familia, pero con ninguno es que como hablar contigo, al grado que eres como una hermana para mí como dice en Proverbios 17:17 “En todo tiempo ama el amigo, Y es como un hermano en tiempo de angustia”, por lo cual es verdad que tengo miedo de perderte. 
Por mi parte tú siempre cuenta conmigo, no importa cuál sea la circunstancia por la que este pasando, tú dime, y haré todo lo posible por responder, y en caso de que no pueda, es porque hay una fuerza mayor que me lo impide, pero siempre haré todo lo posible, y como dice nuestra canción:
“You got troubles, I got them too, there isn’t anything I wouldn’t do for you”
Existe diferencia entre objeto y sujeto, el objeto es objetivo, claro y conciso, no tiene contradicciones; mientras que el sujeto, es el antagónico, porque es subjetivo, no es ni claro ni conciso, y está lleno de contradicciones. Y por eso yo acepto todas tus incoherencias, cuando me dices: se tóxico, y luego: tú eres tóxico. Está bien nadie es coherente, difícil es para el sujeto ser objetivo, si fuéramos objetivos y supiéramos lo que queremos, estaríamos en una utopía, pero no es así, y nuestros errores son los que nos hacen humanos, y por esa razón necesitamos a Dios, para que él desde su perfección nos diga que hacer. Por lo tanto, por tus errores, por tu subjetividad y por tu esencia eres de las personas más importantes en mi vida, siempre te recuerdo en mis oraciones y doy gracias por la entridad que Dios me ha dado contigo. 
Por otro lado, este ya es tu servidor web, para cualquier cosa que puedas necesitar 😉.
Una vez más, gracias por estar ahí, gracias por soportar mis locuras, por soportar lo pesado que soy, por siempre escucharme y por ser tan tú. No sé porque eres mi mejor amiga, pero eso está bien, porque demuestra que es algo que no alcanza el entendimiento lógico. 
Cosa love u so much, eres la mejor, y siempre lo serás, recuerda que los 20 es la edad más atractiva de una mujer, porque atraes a los hombres de todas las edades habidas y por haber, cuidado. 
¡¡¡Pásatela súper en tu cumpleaños!!!
";
$pass = $_POST['pass'];
if($pass === 'auraisthebest131201'){
    echo json_encode($respose);
}else{
    echo json_encode('acceso negado');
}